# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swoop < Formula
  desc "TUI/CLI skill manager for Claude Code + Codex"
  homepage "https://github.com/StreamlinedStartup/skillswoop"
  version "0.1.1"
  license "MIT"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StreamlinedStartup/skillswoop/releases/download/v0.1.1/swoop_0.1.1_darwin_x86_64.tar.gz"
      sha256 "658a73a9061920466f32bf3493c0398936ab3b7ca0894dcc0d74ec762452ec44"

      define_method(:install) do
        bin.install "swoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StreamlinedStartup/skillswoop/releases/download/v0.1.1/swoop_0.1.1_darwin_arm64.tar.gz"
      sha256 "1eab99bf0b832bd887e4895d3b566c134bac35605ac1c8d0c0bf923deb579713"

      define_method(:install) do
        bin.install "swoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StreamlinedStartup/skillswoop/releases/download/v0.1.1/swoop_0.1.1_linux_x86_64.tar.gz"
      sha256 "05cb28aa924bed370bac73140cf9afaaad4145e818995435b6c8022d4627a63b"
      define_method(:install) do
        bin.install "swoop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StreamlinedStartup/skillswoop/releases/download/v0.1.1/swoop_0.1.1_linux_arm64.tar.gz"
      sha256 "735a823d2a235eb3c109824efd176a91288f3501b94835085436245b9cc76920"
      define_method(:install) do
        bin.install "swoop"
      end
    end
  end

  test do
    system "#{bin}/swoop", "--version"
  end
end
