# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swoop < Formula
  desc "TUI/CLI skill manager for Claude Code + Codex"
  homepage "https://github.com/StreamlinedStartup/skillswoop"
  version "0.2.1"
  license "MIT"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StreamlinedStartup/skillswoop/releases/download/v0.2.1/swoop_0.2.1_darwin_x86_64.tar.gz"
      sha256 "fa4c96d0e5b5044c26979b2ab18c01bef397651452addbb13080960e9fc1755c"

      define_method(:install) do
        bin.install "swoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StreamlinedStartup/skillswoop/releases/download/v0.2.1/swoop_0.2.1_darwin_arm64.tar.gz"
      sha256 "8ae55fcd05f9b0fab8995bab8bdd7bd7a8955ce24da6586bce2b5dad07fabbd0"

      define_method(:install) do
        bin.install "swoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StreamlinedStartup/skillswoop/releases/download/v0.2.1/swoop_0.2.1_linux_x86_64.tar.gz"
      sha256 "cba0424b8f1e9f935801c37958798e1bab583cdc76e13d0d2b4fbb660900df19"
      define_method(:install) do
        bin.install "swoop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StreamlinedStartup/skillswoop/releases/download/v0.2.1/swoop_0.2.1_linux_arm64.tar.gz"
      sha256 "f848162f75383167636a93f5a50a70d07c939194442fb2b818ed642e61415d32"
      define_method(:install) do
        bin.install "swoop"
      end
    end
  end

  test do
    system "#{bin}/swoop", "--version"
  end
end
